const netscape= [
'# Netscape HTTP Cookie File',
'# https://curl.haxx.se/docs/http-cookies.html',
'# This file was generated by libcurl! Edit at your own risk.',
'',
'#HttpOnly_.google.de	TRUE	/	FALSE	1621266396	NID	204=hfL629Ehi1_GKPvEJNhsS1P6nPz3al5jwjX7lpmL2mcw7e5kkEJ_cznDP2Qu155OfvdUSeGnbFPrRy90z0WpaSr50RDeuNy02L7LWJcr2ZDlkXfKYfRKnBgW8gcY49IH1uuALyBFm4C0oE2WIStecd5kyFe_61Y9Is6yNmQ-aC4',
''].join("\n");

console.log(JSON.stringify(curl2cookies(netscape),0,2));

// converts a sting containing netscape cookies to an Array
// retrun false if curl or wget signature is not detected
function curl2cookies(text) {
	
	// split text into lines
	var cookies = [];
	var lines = text.split("\n");

	if (! lines[0].toLowerCase().includes("http cookie file")) { return false; }
 
	// iterate over lines
	lines.forEach(function(line, index){
		// split lines imto values
		var tokens = line.split("\t");
 
		// we only care for valid cookie def lines
		if (tokens.length == 7) {
			// trim the tokens
			tokens = tokens.map(function(e){return e.trim();});
			var cookie = {};
			cookie.httpOnly = 'false'; 
			// Extract the data
			cookie.domain = tokens[0];
			if (tokens[0].startsWith("#HttpOnly_")) {
				cookie.domain = tokens[0].replace("#HttpOnly_", '')
				cookie.httpOnly = 'true'; 
			}
			cookie.flag = tokens[1] === 'TRUE';
			cookie.path = tokens[2];
			cookie.secure = tokens[3] === 'TRUE';
 
			// Convert date to a readable format
			var timestamp = tokens[4];
			if (timestamp.length == 17){
				timestamp = Math.floor(timestamp / 1000000 - 11644473600);
			}
			cookie.expiration = timestamp;
			cookie.name = tokens[5];
			cookie.value = tokens[6];
			// Record the cookie.
			cookies.push(cookie);
		}	
	});
	
	return cookies;
}
